In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
all_species = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_all_species.csv"
spruces = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_Picea_abies.csv"
pines = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_Pinus_sylvestris.csv"
firs = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_Abies_alba.csv"
beeches = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_Fagus_sylvatica.csv"
oaks = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\3_classes\3_classes_RGB-RE-NIR\confmat_3-classes_RGB-RE-NIR_Quercus.csv"
class_names = ['healthy', 'stressed', 'dead']

In [3]:
path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB-RE-NIR_plotsplit\droplast_false\confmat_RGB-RE-NIR_combined_14species_plotsplit.csv"
class_names = ['Picea abies healthy', 'Picea abies stressed', 'Pinus sylvestris healthy', 'Pinus sylvestris stressed', 
               'Abies alba healthy', 'Abies alba stressed', 'Fagus sylvatica healthy', 'Fagus sylvatica stressed',
               'Quercus spp. healthy', 'Quercus spp. stressed', 'Larix spp.', 'Acer spp.', 'Betula pendula', 'Dead trees']
output_path_cm = r"C:\Users\lwfeckesim\Downloads\confmat_14-classes_plotsplit.png"

In [28]:
path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB-RE-NIR-CHM_plotsplit\droplast_false\confmat_RGB-RE-NIR-CHM_combined_6classes_plotsplit.csv"
class_names = ['healthy', 'stressed', 'Larix spp.', 'Acer spp.', 'Betula pendula', 'dead']
output_path_cm = r"C:\Users\lwfeckesim\Downloads\confmat_5-classes_plotsplit.png"

In [165]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report

path = r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\confmat_RGB-RE-NIR-CHM_combined_6classes_plotsplit.csv'
num_classes = 6

# Read the CSV file into a DataFrame
df = pd.read_csv(path, header=None)

# Convert the DataFrame to a NumPy array
confusion_matrix = df.values

# Get the number of classes
num_classes = len(df)

# Initialize variables to store true positives, true negatives, false positives, false negatives
tp = np.zeros(num_classes)
tn = np.zeros(num_classes)
fp = np.zeros(num_classes)
fn = np.zeros(num_classes)

# Compute true positives, true negatives, false positives, false negatives
for i in range(num_classes):
    tp[i] = confusion_matrix[i, i]
    tn[i] = np.sum(np.delete(np.delete(confusion_matrix, i, axis=0), i, axis=1))
    fp[i] = np.sum(confusion_matrix[:, i]) - tp[i]
    fn[i] = np.sum(confusion_matrix[i, :]) - tp[i]

# Calculate precision, recall, F1-score, and support
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1_score = 2 * (precision * recall) / (precision + recall)
support = np.sum(confusion_matrix, axis=1)

# Calculate mean F1-score
mean_f1_score = np.mean(f1_score)

# Create a DataFrame for the classification report
report_data = {'precision': precision, 'recall': recall, 'f1-score': f1_score, 'support': support}
report_df = pd.DataFrame(report_data, index=range(num_classes))

# Print the classification report
print(report_df)

# Print the mean F1-score
print("Mean F1-score: {:.2f}".format(mean_f1_score))
# Save the report to a file
df_string = report_df.to_string(index=False)

with open(r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\report_RGB-RE-NIR-CHM_combined_6classes_plotsplit.txt', 'w') as f:
    f.write(df_string)


   precision    recall  f1-score  support
0   0.952965  0.960825  0.956879      485
1   0.932384  0.959707  0.945848      273
2   0.884615  0.676471  0.766667       34
3   0.803279  0.816667  0.809917      120
4   0.789474  0.740741  0.764331       81
5   0.933333  0.903226  0.918033       31
Mean F1-score: 0.86


#### 14 classes to 6 classes (healthy status + 3 species) 

In [124]:
import numpy as np
import csv

path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB_plotsplit\droplast_false\confmat_RGB_combined_14species_plotsplit.csv"

# Define the path to your CSV file
csv_file_path = path

# Read the CSV file using the csv module
with open(csv_file_path, 'r') as file:
    csv_data = csv.reader(file)
    
    # Convert the CSV data into a list
    data_list = list(csv_data)
    
# Convert the data list into a NumPy array
original_matrix = np.array(data_list, dtype=int)

# Print the NumPy array
print(original_matrix)

healthy = original_matrix[[0,2,4,6,8],:].sum(axis=0)
stressed = original_matrix[[1,3,5,7,9],:].sum(axis=0)
larix = original_matrix[10,:]
acer = original_matrix[11,:]
betula = original_matrix[12,:]
dead = original_matrix[13,:]

new_confusion_matrix = np.vstack((healthy, stressed, larix, acer, betula, dead))

healthy = new_confusion_matrix[:,[0,2,4,6,8]].sum(axis=1)
stressed = new_confusion_matrix[:,[1,3,5,7,9]].sum(axis=1)
larix = new_confusion_matrix[:,10]
acer = new_confusion_matrix[:,11]
betula = new_confusion_matrix[:,12]
dead = new_confusion_matrix[:,13]

new_confusion_matrix = np.column_stack((healthy, stressed, larix, acer, betula, dead))

# Save the new confusion matrix as a CSV file
# Convert NumPy array to Pandas DataFrame
df = pd.DataFrame(new_confusion_matrix)
df.to_csv(r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB_plotsplit\droplast_false\confmat_RGB_combined_6classes_plotsplit.csv', header=False, index=False)
print(new_confusion_matrix)

[[277  49   2   3   3   0   0   0   0   0   0   1   2   1]
 [ 52  89   0   0   2   1   0   1   0   0   0   1   1   0]
 [  1   0  34  70   0   0   0   0   1   0   1   0   0   0]
 [  4   0  24 136   0   0   1   0   0   0   0   0   0   1]
 [  1   0   1   0  16   0   1   0   0   0   0   0   0   0]
 [  0   0   0   1   5   7   1   0   1   0   0   0   0   0]
 [  6   0   0   0   1   0  49  14   2   1   0   2   1   0]
 [  0   1   1   0   2   2  10  25   1   0   0   1   1   0]
 [  2   0   0   2   0   0  12   5  33   6   0   1   0   0]
 [  0   1   0   0   0   0   3   2   9   5   0   0   0   0]
 [  7   2  10   1   0   0   1   0   0   0  23   0   1   0]
 [  4   0   0   0   0   0   7   2   2   0   0   5   0   0]
 [  1   1   0   2   0   0   2   0   0   0   0   0   7   0]
 [  1   0   0   1   0   0   0   0   0   0   0   0   0  29]]
[[442 150   1   4   3   1]
 [116 271   0   2   2   1]
 [ 18   3  23   0   1   0]
 [ 13   2   0   5   0   0]
 [  3   3   0   0   7   0]
 [  1   1   0   0   0  29]]


#### 14 classes to 9 classes (species only)

In [147]:
import numpy as np
import csv

path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB-RE-NIR-CHM_plotsplit\droplast_false\confmat_RGB-RE-NIR-CHM_combined_14species_plotsplit.csv"

# Define the path to your CSV file
csv_file_path = path

# Read the CSV file using the csv module
with open(csv_file_path, 'r') as file:
    csv_data = csv.reader(file)
    
    # Convert the CSV data into a list
    data_list = list(csv_data)
    
# Convert the data list into a NumPy array
original_matrix = np.array(data_list, dtype=int)

# Print the NumPy array
print(original_matrix)

picea = original_matrix[[0,1],:].sum(axis=0)
pinus = original_matrix[[2,3],:].sum(axis=0)
abies = original_matrix[[4,5],:].sum(axis=0)
fagus = original_matrix[[6,7],:].sum(axis=0)
quercus = original_matrix[[8,9],:].sum(axis=0)
larix = original_matrix[10,:]
acer = original_matrix[11,:]
betula = original_matrix[12,:]
dead = original_matrix[13,:]

new_confusion_matrix = np.vstack((picea, pinus, abies, fagus, quercus, larix, acer, betula, dead))

picea = new_confusion_matrix[:,[0,1]].sum(axis=1)
pinus = new_confusion_matrix[:,[2,3]].sum(axis=1)
abies = new_confusion_matrix[:,[4,5]].sum(axis=1)
fagus = new_confusion_matrix[:,[6,7]].sum(axis=1)
quercus = new_confusion_matrix[:,[8,9]].sum(axis=1)
larix = new_confusion_matrix[:,10]
acer = new_confusion_matrix[:,11]
betula = new_confusion_matrix[:,12]
dead = new_confusion_matrix[:,13]

new_confusion_matrix = np.column_stack((picea, pinus, abies, fagus, quercus, larix, acer, betula, dead))

# Save the new confusion matrix as a CSV file
# Convert NumPy array to Pandas DataFrame
df = pd.DataFrame(new_confusion_matrix)
df.to_csv(r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\14-classes_plotsplit\14-classes_RGB-RE-NIR-CHM_plotsplit\droplast_false\confmat_RGB-RE-NIR-CHM_combined_9classes_plotsplit.csv', header=False, index=False)
print(new_confusion_matrix)

[[277  40   9   2   3   0   2   1   0   0   3   0   1   0]
 [ 43  93   3   2   0   0   0   0   0   0   6   0   0   0]
 [  2   0  55  47   1   0   0   0   1   0   1   0   0   0]
 [  2   0  67  95   0   0   0   0   0   0   1   0   0   1]
 [  4   0   1   0  11   1   1   1   0   0   0   0   0   0]
 [  2   1   0   1   5   5   0   0   0   0   1   0   0   0]
 [  5   0   3   0   0   0  43  15   8   1   0   0   1   0]
 [  1   0   1   0   0   0   9  27   2   3   0   0   1   0]
 [  1   0   1   0   0   0   8   4  37   7   0   2   1   0]
 [  0   0   0   0   0   0   0   2  10   7   0   1   0   0]
 [  1   2  10   3   4   0   1   0   0   0  24   0   0   0]
 [  2   0   2   0   0   0   9   1   4   0   0   2   0   0]
 [  1   0   0   1   0   0   4   0   0   0   1   0   6   0]
 [  2   0   0   1   0   0   0   0   0   0   0   0   0  28]]
[[453  16   3   3   0   9   0   1   0]
 [  4 264   1   0   1   2   0   0   1]
 [  7   2  22   2   0   1   0   0   0]
 [  6   4   0  94  14   0   0   2   0]
 [  1   1   0  14

#### 11 classes to 6 classes (species only) 

In [157]:
import numpy as np
import csv

path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\confmat_RGB-RE-NIR-CHM_combined_11classes_plotsplit.csv"

# Define the path to your CSV file
csv_file_path = path

# Read the CSV file using the csv module
with open(csv_file_path, 'r') as file:
    csv_data = csv.reader(file)
    
    # Convert the CSV data into a list
    data_list = list(csv_data)
    
# Convert the data list into a NumPy array
original_matrix = np.array(data_list, dtype=int)

# Print the NumPy array
print(original_matrix)

picea = original_matrix[[0,1],:].sum(axis=0)
pinus = original_matrix[[2,3],:].sum(axis=0)
abies = original_matrix[[4,5],:].sum(axis=0)
fagus = original_matrix[[6,7],:].sum(axis=0)
quercus = original_matrix[[8,9],:].sum(axis=0)
dead = original_matrix[10,:]

new_confusion_matrix = np.vstack((picea, pinus, abies, fagus, quercus, dead))

picea = new_confusion_matrix[:,[0,1]].sum(axis=1)
pinus = new_confusion_matrix[:,[2,3]].sum(axis=1)
abies = new_confusion_matrix[:,[4,5]].sum(axis=1)
fagus = new_confusion_matrix[:,[6,7]].sum(axis=1)
quercus = new_confusion_matrix[:,[8,9]].sum(axis=1)
dead = new_confusion_matrix[:,10]

new_confusion_matrix = np.column_stack((picea, pinus, abies, fagus, quercus, dead))

# Save the new confusion matrix as a CSV file
# Convert NumPy array to Pandas DataFrame
df = pd.DataFrame(new_confusion_matrix)
df.to_csv(r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\confmat_RGB-RE-NIR-CHM_combined_6classes_plotsplit.csv', header=False, index=False)
print(new_confusion_matrix)

[[287  37   9   2   2   0   0   1   0   0   0]
 [ 53  89   4   1   0   0   0   0   0   0   0]
 [  2   0  53  50   1   0   1   0   0   0   0]
 [  3   2  60  99   0   0   0   0   0   0   2]
 [  3   0   0   1  11   2   1   1   0   0   0]
 [  2   3   0   0   3   7   0   0   0   0   0]
 [  4   1   1   0   0   0  44  16   9   1   0]
 [  0   0   0   0   0   0  10  28   3   3   0]
 [  1   0   0   0   0   0  11   5  40   4   0]
 [  0   0   0   0   0   0   0   4   8   8   0]
 [  2   0   0   1   0   0   0   0   0   0  28]]
[[466  16   2   1   0   0]
 [  7 262   1   1   0   2]
 [  8   1  23   2   0   0]
 [  5   1   0  98  16   0]
 [  1   0   0  20  60   0]
 [  2   1   0   0   0  28]]


#### 11 classes to 3 classes (health status only) 

In [129]:
import numpy as np
import csv

path = r"C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\confmat_RGB-RE-NIR-CHM_combined_11classes_plotsplit.csv"

# Define the path to your CSV file
csv_file_path = path

# Read the CSV file using the csv module
with open(csv_file_path, 'r') as file:
    csv_data = csv.reader(file)
    
    # Convert the CSV data into a list
    data_list = list(csv_data)
    
# Convert the data list into a NumPy array
original_matrix = np.array(data_list, dtype=int)

# Print the NumPy array
print(original_matrix)

healthy = original_matrix[[0,2,4,6,8],:].sum(axis=0)
stressed = original_matrix[[1,3,5,7,9],:].sum(axis=0)
#larix = original_matrix[10,:]
#acer = original_matrix[11,:]
#betula = original_matrix[12,:]
dead = original_matrix[10,:]

new_confusion_matrix = np.vstack((healthy, stressed, dead))

healthy = new_confusion_matrix[:,[0,2,4,6,8]].sum(axis=1)
stressed = new_confusion_matrix[:,[1,3,5,7,9]].sum(axis=1)
#larix = new_confusion_matrix[:,10]
#acer = new_confusion_matrix[:,11]
#betula = new_confusion_matrix[:,12]
dead = new_confusion_matrix[:,10]

new_confusion_matrix = np.column_stack((healthy, stressed, dead))

# Save the new confusion matrix as a CSV file
# Convert NumPy array to Pandas DataFrame
df = pd.DataFrame(new_confusion_matrix)
df.to_csv(r'C:\Users\lwfeckesim\01_PyTorch\wze-uav\wze-uav-master\plots\11-classes_plotsplit\RGB-RE-NIR-CHM\confmat_RGB-RE-NIR-CHM_combined_3classes_plotsplit.csv', header=False, index=False)
print(new_confusion_matrix)

[[287  37   9   2   2   0   0   1   0   0   0]
 [ 53  89   4   1   0   0   0   0   0   0   0]
 [  2   0  53  50   1   0   1   0   0   0   0]
 [  3   2  60  99   0   0   0   0   0   0   2]
 [  3   0   0   1  11   2   1   1   0   0   0]
 [  2   3   0   0   3   7   0   0   0   0   0]
 [  4   1   1   0   0   0  44  16   9   1   0]
 [  0   0   0   0   0   0  10  28   3   3   0]
 [  1   0   0   0   0   0  11   5  40   4   0]
 [  0   0   0   0   0   0   0   4   8   8   0]
 [  2   0   0   1   0   0   0   0   0   0  28]]
[[480 121   0]
 [146 244   2]
 [  2   1  28]]
